"""Paper exporter — assembles all task outputs into a complete paper."""

from pathlib import Path
from typing import Dict, Any

from .context import ContextManager


class PaperExporter:
    """Gathers all approved task outputs and assembles them into a paper.

    Supports both LaTeX (PRD/JHEP style) and Markdown output formats.
    """

    def __init__(self, config: Dict[str, Any]):
        output_cfg = config.get("output", {})
        self.paper_dir = Path(output_cfg.get("paper_dir", "paper"))
        self.context_file = output_cfg.get("context_file", "outputs/context.json")
        self.project_name = config.get("project", {}).get("name", "AI4Sci Project")
        self.paper_dir.mkdir(parents=True, exist_ok=True)

    def export_latex(self) -> str:
        """Export paper as LaTeX source file."""
        ctx = ContextManager(self.context_file)
        ctx.load()
        results = ctx.get_approved_tasks()

        sections = self._build_latex_sections(results)
        latex = self._latex_template(sections)

        output_path = self.paper_dir / "paper.tex"
        output_path.write_text(latex, encoding="utf-8")
        return str(output_path)

    def export_markdown(self) -> str:
        """Export paper as Markdown file."""
        ctx = ContextManager(self.context_file)
        ctx.load()
        results = ctx.get_approved_tasks()

        sections = self._build_markdown_sections(results)
        markdown = self._markdown_template(sections)

        output_path = self.paper_dir / "paper.md"
        output_path.write_text(markdown, encoding="utf-8")
        return str(output_path)

    def _build_latex_sections(self, results) -> str:
        """Build LaTeX sections from task results."""
        sections = []
        for r in results:
            section = f"% ============================================================\n"
            section += f"% Section from Task {r.task_id}: {r.title}\n"
            section += f"% Agent: {r.agent}\n"
            section += f"% ============================================================\n"
            # Task output is in Markdown/LaTeX mixed format; include as-is with LaTeX wrapper
            output = r.output
            # Escape any unescaped underscores outside math mode (simplistic)
            section += output
            sections.append(section)
        return "\n\n".join(sections)

    def _build_markdown_sections(self, results) -> str:
        """Build Markdown sections from task results."""
        sections = []
        for r in results:
            section = f"## Section from Task {r.task_id}: {r.title}\n\n"
            section += f"*Agent: {r.agent} | Approved: {r.timestamp}*\n\n"
            section += r.output
            sections.append(section)
        return "\n\n---\n\n".join(sections)

    def _latex_template(self, sections: str) -> str:
        return rf"""\documentclass[aps,prd,reprint]{{revtex4-2}}
\usepackage{{amsmath,amssymb}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{hyperref}}

\begin{{document}}

\title{{{self.project_name}}}
\author{{AI4Sci Harness Collaboration}}
\date{{\today}}

\begin{{abstract}}
% TODO: Replace with your project abstract (generated by Writer Agent in Task 6)
This paper was generated using the AI4Sci 5-Node Multi-Agent Research Collaboration Framework.
\end{{abstract}}

\maketitle

\tableofcontents

{sections}

\begin{{thebibliography}}{{99}}
% 参考文献由 Writer 整合时加入
\end{{thebibliography}}

\end{{document}}
"""

    def _markdown_template(self, sections: str) -> str:
        return f"""# {self.project_name}

**Generated by AI4Sci Harness — 5-Node Multi-Agent Research Collaboration Framework**

---

## Abstract

<!-- TODO: Replace with your project abstract (generated by Writer Agent in Task 6) -->

---

{sections}

---

## References

*References integrated by Writer Agent*
"""
