"""Sandbox — isolated Python code execution environment."""

import subprocess
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional


@dataclass
class SandboxResult:
    success: bool
    exit_code: int
    stdout: str
    stderr: str
    output_files: List[str] = field(default_factory=list)
    error_message: str = ""


class Sandbox:
    """Isolated execution environment for Executor-produced Python code.

    Runs code in a subprocess with timeout, output capture, and
    import security checks.
    """

    def __init__(self, config: dict):
        sandbox_cfg = config.get("sandbox", {})
        self.timeout = sandbox_cfg.get("timeout", 300)
        self.max_output = sandbox_cfg.get("max_output_bytes", 1_048_576)
        self.allowed_imports = set(sandbox_cfg.get("allowed_imports", []))
        self.blocked_imports = set(sandbox_cfg.get("blocked_imports", []))
        self.python_path = sandbox_cfg.get("python_path", "python3")
        self.sandbox_dir = Path(config.get("output", {}).get("sandbox_dir", "sandbox"))
        self.sandbox_dir.mkdir(parents=True, exist_ok=True)

    def run(self, code: str, task_id: int = 0) -> SandboxResult:
        """Execute Python code in a sandboxed subprocess.

        Args:
            code: Python source code to execute.
            task_id: Task number for labeling output files.

        Returns:
            SandboxResult with exit code, stdout, stderr, and any generated files.
        """

        # Security: check for blocked imports before execution
        blocked = self._check_imports(code)
        if blocked:
            return SandboxResult(
                success=False,
                exit_code=-1,
                stdout="",
                stderr="",
                error_message=f"Blocked imports detected: {', '.join(blocked)}",
            )

        # Record files before execution to detect new ones
        before_files = set(self.sandbox_dir.rglob("*"))

        # Write code to a temp file and execute
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", dir=self.sandbox_dir,
            delete=False, encoding="utf-8",
        ) as f:
            f.write(code)
            script_path = f.name

        try:
            result = subprocess.run(
                [self.python_path, script_path],
                capture_output=True,
                timeout=self.timeout,
                cwd=str(self.sandbox_dir),
                text=True,
            )

            # Truncate output if too large
            stdout = result.stdout[:self.max_output]
            stderr = result.stderr[:self.max_output]

            # Detect new files generated by the script
            after_files = set(self.sandbox_dir.rglob("*"))
            new_files = sorted(
                str(p.relative_to(self.sandbox_dir))
                for p in (after_files - before_files)
                if p.name != Path(script_path).name
            )

            return SandboxResult(
                success=(result.returncode == 0),
                exit_code=result.returncode,
                stdout=stdout,
                stderr=stderr,
                output_files=new_files,
            )

        except subprocess.TimeoutExpired:
            return SandboxResult(
                success=False,
                exit_code=-1,
                stdout="",
                stderr="",
                error_message=f"Execution timed out after {self.timeout}s",
            )

        finally:
            # Clean up the temp script
            try:
                Path(script_path).unlink()
            except OSError:
                pass

    def _check_imports(self, code: str) -> List[str]:
        """Scan code for blocked import statements. Returns list of violations."""
        import re
        violations = []

        # Check import statements — capture only valid module name chars
        import_patterns = [
            r'^\s*import\s+([a-zA-Z_][a-zA-Z0-9_.]*)',
            r'^\s*from\s+([a-zA-Z_][a-zA-Z0-9_.]*)\s+import',
        ]

        for line in code.split('\n'):
            for pattern in import_patterns:
                match = re.match(pattern, line.strip())
                if match:
                    module = match.group(1)
                    # Check blocked list
                    for blocked in self.blocked_imports:
                        if module == blocked or module.startswith(blocked + '.'):
                            violations.append(module)

                    # If allowed list is non-empty, check against it
                    if self.allowed_imports:
                        allowed = any(
                            module == a or module.startswith(a + '.')
                            for a in self.allowed_imports
                        )
                        if not allowed and module not in violations:
                            violations.append(module)

        return violations
